version: 2.1

workflows:
  version: 2
  commit-build:
    jobs:
    - lint
    - tests-python35
    - tests-python36
    - tests-python37
    - tests-python38

jobs:
  lint:
    docker:
    - image: circleci/python:3.6
    steps:
    - checkout
    - run:
        name: install tox
        command: pip install tox --user
    - run:
        name: run tox -e lint
        command: tox -e lint

  tests-python35:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: install tox
          command: pip install tox --user
      - run:
          name: run tox -e py35
          command: tox -e py35

  tests-python36:
    docker:
    - image: circleci/python:3.6
    steps:
    - checkout
    - run:
        name: install tox
        command: pip install tox --user
    - run:
        name: run tox -e py36
        command: tox -e py36

  tests-python37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install tox
          command: pip install tox --user
      - run:
          name: run tox -e py37
          command: tox -e py37

  tests-python38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install tox
          command: pip install tox --user
      - run:
          name: run tox -e py38
          command: tox -e py38
